title: Haolin Liu's Homepage
page-top-title: Haolin Liu
top-section-bg-text: Intelligent Science and Technology
home-subtitle: Haolin Liu&ensp;|&ensp;刘浩琳
copyright-text: '&copy; Haolin Liu 2026-2030. All Rights Reserved.'
